server:
  port: 8989
  servlet:
    context-path: /cmfz
  jsp:    #jsp页面热部署
    init-parameters:
      development: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  servlet:
    multipart:
      enabled: true
      max-file-size: 500mb
      max-request-size: 500mb
  mvc:
    view:
      suffix: .jsp
      prefix: /
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapping/*.xml